### ISSUE TITLE
Add extra constructor to BaseTrackState

### ISSUE THREAD

**Issue by mdiamon** [slaclab/lcsim#9]
I'd like to add an extra constructor to BaseTrackState.java , which takes only one parameter:
public BaseTrackState(int location)
{ _location = location; }
This would allow me to create "dummy" TrackStates with location -1, to represent unhit sensors in List<TrackState>.  Setting the location to -1 is OK everywhere except in BaseTrackState.SetLocation(), which is called by the BaseTrackState constructors and requires the location to be 0 to 5; the extra constructor bypasses this check.

**Comment by JeremyMcCormick** [comment]
Resolved by PR #10.

**Comment by mdiamon** [comment]
Unfortunately we do need to change the SetLocation() to allow -1, because it gets called when recreating TrackStates from lcio files being read back in by certain hps-java tools.
